"""
doc_generator.py — Orchestrates the full documentation sync workflow.

Handles two event paths:
1. pull_request (closed + merged): Analyze the diff, generate doc update, open a draft PR.
2. issue_comment (created on a PR): If it's a /doc-sync command, refine the doc update.
"""
import re
from src.config import Config
from src.github_client import GitHubClient
from src.llm_client import LLMClient

# Map of doc hint keywords -> relative doc file paths inside the website repo
DOC_HINT_MAP = {
    "scenarios": "content/en/docs/scenarios/_tab-krkn.md",
    "configuration": "content/en/docs/configuration/index.md",
    "cli": "content/en/docs/configuration/index.md",  # fallback to config page
    "general": "content/en/docs/configuration/index.md",
}

BOT_PR_BRANCH_PREFIX = "krkn-doc-bot/"
BOT_PR_TITLE_PREFIX = "[Doc Bot]"


def _make_branch_name(pr_number: int, upstream_repo: str) -> str:
    safe_repo = upstream_repo.replace("/", "-")
    return f"{BOT_PR_BRANCH_PREFIX}{safe_repo}-pr-{pr_number}"


def handle_pr_merged(event: dict, config: Config, gh: GitHubClient, llm: LLMClient) -> None:
    """
    Called when a PR is merged in an upstream repository.
    Analyzes the diff, generates documentation, and opens a draft PR on the website repo.
    """
    pr_data = event["pull_request"]
    pr_number = pr_data["number"]
    pr_title = pr_data["title"]
    pr_body = pr_data.get("body") or ""
    upstream_repo_name = event["repository"]["full_name"]

    print(f"[DocBot] Processing merged PR #{pr_number}: '{pr_title}' from {upstream_repo_name}")

    upstream_repo = gh.get_repo(upstream_repo_name)
    diff = gh.get_pr_diff(upstream_repo, pr_number)

    print("[DocBot] Analyzing diff with LLM...")
    analysis = llm.analyze_diff(diff, pr_title, pr_body)
    print(f"[DocBot] Analysis: needs_update={analysis.get('needs_update')}, hint={analysis.get('affected_doc_hint')}")

    if not analysis.get("needs_update"):
        print(f"[DocBot] No documentation update needed. Reason: {analysis.get('reason')}")
        return

    # Determine which doc file to update
    hint = analysis.get("affected_doc_hint", "general").lower()
    doc_path = DOC_HINT_MAP.get(hint, DOC_HINT_MAP["general"])
    print(f"[DocBot] Targeting website doc file: {doc_path}")

    website_repo = gh.get_repo(config.website_repo)
    current_content, file_sha = gh.get_file_content(website_repo, doc_path)

    print("[DocBot] Generating updated documentation with LLM...")
    updated_content = llm.generate_doc_update(analysis["change_summary"], current_content)

    # Create branch and commit
    branch_name = _make_branch_name(pr_number, upstream_repo_name)
    gh.create_branch(website_repo, branch_name)
    gh.commit_file(
        website_repo,
        doc_path,
        updated_content,
        f"docs: auto-update {doc_path} based on {upstream_repo_name}#{pr_number}",
        branch_name,
        file_sha,
    )

    # Build PR body
    upstream_pr_url = pr_data.get("html_url", "")
    pr_body_text = f"""## 🤖 Automated Documentation Update

This PR was automatically generated by the **Krkn Doc Sync Bot**.

**Triggered by:** [{upstream_repo_name}#{pr_number}]({upstream_pr_url}) — _{pr_title}_

**Summary of changes detected:**
{analysis.get('change_summary', '')}

**Doc file updated:** `{doc_path}`

---
> To refine this documentation, comment on this PR with:
> `/doc-sync <your instruction>`
> Example: `/doc-sync Add a note that this parameter is optional`
"""

    # Check if draft PR already exists (idempotency)
    existing_pr = gh.find_existing_bot_pr(website_repo, branch_name)
    if existing_pr:
        print(f"[DocBot] Draft PR already exists: {existing_pr.html_url}")
        gh.post_comment(existing_pr, "🔄 Bot has updated the documentation based on a new upstream change.")
    else:
        pr_title_full = f"{BOT_PR_TITLE_PREFIX} Update docs for {upstream_repo_name}#{pr_number}"
        new_pr = gh.create_draft_pr(website_repo, pr_title_full, pr_body_text, branch_name)
        print(f"[DocBot] Draft PR created: {new_pr.html_url}")


def handle_issue_comment(event: dict, config: Config, gh: GitHubClient, llm: LLMClient) -> None:
    """
    Called when a comment is posted on a PR on the website repo.
    If the comment is a /doc-sync command, refines the documentation.
    """
    comment_body = event["comment"]["body"]
    if not gh.is_bot_command(comment_body):
        print("[DocBot] Comment is not a bot command, ignoring.")
        return

    instruction = gh.parse_bot_command(comment_body)
    if not instruction:
        print("[DocBot] Empty /doc-sync instruction, ignoring.")
        return

    print(f"[DocBot] Refinement requested: '{instruction}'")

    pr_number = event["issue"]["number"]
    website_repo = gh.get_repo(config.website_repo)
    pr = gh.get_pr(website_repo, pr_number)

    # Find the doc file modified in this PR
    pr_files = list(pr.get_files())
    if not pr_files:
        gh.post_comment(pr, "⚠️ Could not find any files modified in this PR to refine.")
        return

    # Take the first modified file as the target (bot PRs modify one file)
    target_file = pr_files[0]
    doc_path = target_file.filename
    branch_name = pr.head.ref

    current_content, file_sha = gh.get_file_content(website_repo, doc_path, ref=branch_name)
    if not current_content:
        gh.post_comment(pr, f"⚠️ Could not read `{doc_path}` from branch `{branch_name}`.")
        return

    print(f"[DocBot] Refining doc: {doc_path} on branch {branch_name}")
    refined_content = llm.refine_doc_update(instruction, current_content)

    gh.commit_file(
        website_repo,
        doc_path,
        refined_content,
        f"docs: refine {doc_path} based on reviewer instruction",
        branch_name,
        file_sha,
    )

    gh.post_comment(pr, f"✅ Documentation refined based on your instruction:\n> _{instruction}_\n\nPlease review the latest commit.")
    print("[DocBot] Refinement committed and comment posted.")
